In [ ]:
# First deep learning
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([2,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[2,6,8],
                     [3,2,1],
                     [4,2,5]])

matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 6, 8],
       [3, 2, 1],
       [4, 2, 5]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor = tf.constant([[[2.5, 3.4, 7.6, 5.4],
                      [2.3, 7.8, 9.2, 7.4],
                      [2.6, 8.4, 3.3, 2.1]],

                     [[2.3, 6.7, 8.8, 9.7],
                      [3.4, 2.2, 4.2, 5.1],
                      [9.8, 6.7, 8.2, 2.6]],

                     [[2.3, 1.4, 5.3, 8.9],
                      [3.2, 1.5, 7.6, 8.9],
                      [2.8, 5.8, 9.3, 7.8]]],dtype=tf.float16)

tensor

<tf.Tensor: shape=(3, 3, 4), dtype=float16, numpy=
array([[[2.5, 3.4, 7.6, 5.4],
        [2.3, 7.8, 9.2, 7.4],
        [2.6, 8.4, 3.3, 2.1]],

       [[2.3, 6.7, 8.8, 9.7],
        [3.4, 2.2, 4.2, 5.1],
        [9.8, 6.7, 8.2, 2.6]],

       [[2.3, 1.4, 5.3, 8.9],
        [3.2, 1.5, 7.6, 8.9],
        [2.8, 5.8, 9.3, 7.8]]], dtype=float16)>

In [ ]:
tensor.ndim

3

### MEMBUAT TENSOR MENGGUNAKAN tf.Variable

kali ini saya akan membuat tensor menggunakan tf.Variable dan juga saya akan mengubah elemen dalam tensor, yaitu menggunakan 2 method yaitu tf.constant dan tf.Variable

In [ ]:
# Membuat tensor dengan tf.Variable

tensor_bisa_diubah = tf.Variable([10,7,8,9,6])
tensor_tidak_bisa_diubah = tf.constant([10,7,8,9,6])
tensor_bisa_diubah, tensor_tidak_bisa_diubah



(<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10,  7,  8,  9,  6], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([10,  7,  8,  9,  6], dtype=int32)>)

In [ ]:
# sekarang kita ubah semua elemen tf.Variable
tensor_bisa_diubah.assign([1,2,3,4,5])
tensor_bisa_diubah

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
# sekarang kita ubah salah satu elemen tf.Variable
tensor_bisa_diubah[1].assign(9)
tensor_bisa_diubah

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 9, 3, 4, 5], dtype=int32)>

In [ ]:
# sekarang kita ubah elemen tf.constant
tensor_tidak_bisa_diubah.assign([1,2,3,4,5])
tensor_tidak_bisa_diubah

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

ini menjelaskan bahwa tf.constant elemennya tidak bisa diubah karena sudah bersifat mutlak

### MEMBUAT RANDOM TENSOR

Jadi kali ini saya ingin membuat random tensor, ini sangat diperlukan dalam deep learning, cara membuat random tensor adalah dengan memberikan seed pada tensor tersebut agar memiliki elemen (itu sepengetahuan saya)



In [ ]:
# saya akan membuat dua tensor random tapi kedua elemen tersebut sama dengan cara memberikan seed pada tensor tersebut
random_1 = tf.random.Generator.from_seed(50) # angkanya bebas yang penting bilangan integer, saya pakai 50 karena itu angka favorit saya
random_1 = random_1.normal(shape=(3,3))
random_2 = tf.random.Generator.from_seed(50)
random_2 = random_2.normal(shape=(3,3))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ,  1.0034493 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ,  1.0034493 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

Di sini membuktikan bahwa jika kita memberikan seed kepada tensor yang random maka tensor tersebut akan memiliki nilai namun saya memberikan seed yang sama kepada 2 tensor tersebut makanya random_1 dan random_2 memiliki nilai yang sama

In [ ]:
# kita coba membuat 2 random tensor lagi dengan kedua seed yang berbeda
random_3 = tf.random.Generator.from_seed(49)
random_3 = random_3.normal(shape=(3, 3))
random_4 = tf.random.Generator.from_seed(50)
random_4 = random_4.normal(shape=(3, 3))

random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.5184573 , -0.4585211 ,  0.5714663 ],
        [-1.5331722 ,  0.45331386,  1.1487608 ],
        [-1.2659091 , -0.47450137,  2.006022  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ,  1.0034493 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

random_3 dan random_4 memiliki nilai yang berbeda itu karena random_3 dan random_4 memiliki seed yang berbeda

### MENGACAK URUTAN TENSOR

kali ini saya akan membuat tensor tapi mengacak urutannya menggunakan tf.random.shuffle

In [ ]:
# kita buat tensor nya dahulu
tensor_nonacak = tf.constant([[2, 3, 4],
                              [5, 4, 3],
                              [7, 8, 9]])

tensor_nonacak

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 4, 3],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# sekarang kita ubah urutannya menggunakan tf.random.shuffle
tf.random.shuffle(tensor_nonacak)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 4, 3],
       [7, 8, 9]], dtype=int32)>

sekarang kita sudah mengubah urutannya, urutannya akan terus berubah apabila kita klik run secara berkali kali, lalu bagaimana cara agar tensor tersebut tidak teracak? lihat tutor di bawah ini

In [ ]:
# kita pasang seed pada tensor tersebut
tf.random.set_seed(50) # angkanya bebas asal bilangan integer

tf.random.shuffle(tensor_nonacak)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [5, 4, 3],
       [2, 3, 4]], dtype=int32)>

sekarang tensor tersebut tidak akan teracak apabila kita klik run berkali kali

### MEMBUAT TENSOR MENGGUNAKAN NUMPY

kali ini saya akan membuat tensor menggunakan tensor menggunakan numpy, apa bedanya tensor dengan numpy? sebanarnya tidak ada perbedaan yang mencolok tapi yang membedakan adalah tensor berjalan di gpu perangkat agar proses komputasi lebih cepat

In [ ]:
# kita import dulu library numpy nya dahulu,lalu kita buat array dari numpy
import numpy as np

numpy1 = np.arange(1, 61, dtype=np.int32)
numpy1, numpy1.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int32),
 (60,))

In [ ]:
# lalu kita buat tensor dari numpy array yang kita buat
a = tf.constant(numpy1, shape=(3, 5, 4)) # di sini saya membuat tensor dalam bentuk matrix
b = tf.constant(numpy1) # di sini saya membuat tensor dalam bentuk array biasa

a, b

(<tf.Tensor: shape=(3, 5, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20]],
 
        [[21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36],
         [37, 38, 39, 40]],
 
        [[41, 42, 43, 44],
         [45, 46, 47, 48],
         [49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60]]], dtype=int32)>,
 <tf.Tensor: shape=(60,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int32)>)

### MACAM MACAM TENSOR

kali ini saya akan membuat tensor dalam berbagai macam bentuk yang pertama tensor yang berisi elemen angka 1 dan yang kedua tensor yang berisi elemen angka 0, mungkin masih ada jenis tensor yang lain yang belum saya ketahui tapi kali saya akan membuat 2 jenis tensor

In [ ]:
# membuat tensor berisi elemen angka 1
tf.ones(shape=(2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
# membuat tensor berisi elemen angka 0
tf.zeros(shape=(3, 4, 5))

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

### MENGAMBIL INFORMASI DARI TENSOR

Kali ini saya akan mengambil informasi dari tensor seperti mengambil shape,dimensi, ukuran atau total elemen dari tensor, dan tipe datanya

In [ ]:
# kita buat dulu arraynya

tensor_1 = np.arange(1, 201, 2, dtype=np.int32)
tensor_1, tensor_1.shape

(array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
        105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
        131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
        157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
        183, 185, 187, 189, 191, 193, 195, 197, 199], dtype=int32),
 (100,))

In [ ]:
# lalu kita buat tensornya

tensor_1 = tf.constant(tensor_1, shape=(4, 5, 5))
tensor_1

<tf.Tensor: shape=(4, 5, 5), dtype=int32, numpy=
array([[[  1,   3,   5,   7,   9],
        [ 11,  13,  15,  17,  19],
        [ 21,  23,  25,  27,  29],
        [ 31,  33,  35,  37,  39],
        [ 41,  43,  45,  47,  49]],

       [[ 51,  53,  55,  57,  59],
        [ 61,  63,  65,  67,  69],
        [ 71,  73,  75,  77,  79],
        [ 81,  83,  85,  87,  89],
        [ 91,  93,  95,  97,  99]],

       [[101, 103, 105, 107, 109],
        [111, 113, 115, 117, 119],
        [121, 123, 125, 127, 129],
        [131, 133, 135, 137, 139],
        [141, 143, 145, 147, 149]],

       [[151, 153, 155, 157, 159],
        [161, 163, 165, 167, 169],
        [171, 173, 175, 177, 179],
        [181, 183, 185, 187, 189],
        [191, 193, 195, 197, 199]]], dtype=int32)>

In [ ]:
# sekarang kita ambil informasi dari tensor dengan beberapa metode
print(f"tipe data dari tensor : {tensor_1.dtype}")
print(f"dimensi dari tensor : {tensor_1.ndim}")
print(f"shape dari tensor : {tensor_1.shape}")
# saya menambahkan [0][0][0] agar bisa mengakses satu elemen karena jika saya menggunakan [0] maka outputnya menghasilkan matrix yang panjang
print(f"elemen pertama dari tensor : {tensor_1[0][0][0]}")
# begitu juga yang ini saya menambahkan [-1][-1][-1] agar bisa mengakses satu elemen karena jika saya menggunakan [-1] maka outputnya menghasilkan matrix yang panjang
print(f"elemen pertama dari tensor : {tensor_1[-1][-1][-1]}")
print(f"total dari seluruh elemen (4*5*5) : {tf.size(tensor_1).numpy()} elemen") # disini saya menambahkan method numpy() supaya output lebih bersih

tipe data dari tensor : <dtype: 'int32'>
dimensi dari tensor : 3
shape dari tensor : (4, 5, 5)
elemen pertama dari tensor : 1
elemen pertama dari tensor : 199
total dari seluruh elemen (4*5*5) : 100 elemen


### INDEX TENSOR

Kali ini saya akan mengakses indes dari tensor menggunakan beberapa cara


In [ ]:
# kita ambil 3 elemen pertama dari masing masing shape, saya mengambilnya dari tensor yang sudah ada di atas
tensor_1[:3, :3, :3]

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[  1,   3,   5],
        [ 11,  13,  15],
        [ 21,  23,  25]],

       [[ 51,  53,  55],
        [ 61,  63,  65],
        [ 71,  73,  75]],

       [[101, 103, 105],
        [111, 113, 115],
        [121, 123, 125]]], dtype=int32)>

In [ ]:
tensor_1.shape

TensorShape([4, 5, 5])

In [ ]:
# kita ambil 2 elemen pertama di setiap shape kecuali shape terakhir
tensor_1[:2, :2, :]

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]],

       [[51, 53, 55, 57, 59],
        [61, 63, 65, 67, 69]]], dtype=int32)>

di sini output yang keluar hanyak 2 matrix atau 2 dimensi karena kita hanya mengakses 2 dimensi nya saja, pada dimensi terakhir bertuliskan 5 karena pada dimensi terakhir kita tidak mengambil indeksnya, makanya bertuliskan 5

In [ ]:
# kita juga bisa mengakses seluruh elemen pada kolom dan baris tertentu

# mengakses setiap elemen pada baris tertentu
last_element_1 = tensor_1[0][:, -2].numpy() # 0 pada kurung kotak pertama adalah matrix pertama
last_element_2 = tensor_1[0][0, -1].numpy()

# mengakses setiap elemen pada kolom tertentu
last_element_3 = tensor_1[0][-1, :].numpy()
last_element_4 = tensor_1[0][-2, 3].numpy()

last_element_1, last_element_2, last_element_3, last_element_4

(array([ 7, 17, 27, 37, 47], dtype=int32),
 9,
 array([41, 43, 45, 47, 49], dtype=int32),
 37)

In [ ]:
# kita bisa menambahkan dimensi tambahan pada tensor
extra_dimensi = tensor_1[tf.newaxis, ...]
extra_dimensi

<tf.Tensor: shape=(1, 4, 5, 5), dtype=int32, numpy=
array([[[[  1,   3,   5,   7,   9],
         [ 11,  13,  15,  17,  19],
         [ 21,  23,  25,  27,  29],
         [ 31,  33,  35,  37,  39],
         [ 41,  43,  45,  47,  49]],

        [[ 51,  53,  55,  57,  59],
         [ 61,  63,  65,  67,  69],
         [ 71,  73,  75,  77,  79],
         [ 81,  83,  85,  87,  89],
         [ 91,  93,  95,  97,  99]],

        [[101, 103, 105, 107, 109],
         [111, 113, 115, 117, 119],
         [121, 123, 125, 127, 129],
         [131, 133, 135, 137, 139],
         [141, 143, 145, 147, 149]],

        [[151, 153, 155, 157, 159],
         [161, 163, 165, 167, 169],
         [171, 173, 175, 177, 179],
         [181, 183, 185, 187, 189],
         [191, 193, 195, 197, 199]]]], dtype=int32)>

kini dimensi nya bertambah menjadi 4 dimensi

# OPERASI TENSOR

kita bisa mengalikan, membagi dan operasi matematika lainnya pada tensor


In [ ]:
# kita buat tensor nya dahulu
tensor_ex = np.arange(1, 10, dtype=np.int32)
tensor_ex = tf.constant(tensor_ex, shape=(3, 3))
tensor_ex

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# kita gunakan operasi tambah
x = tensor_ex + 10

# kita gunakan operasi kurang
y = tensor_ex - 1

# kita gunakan operasi kali
z = tensor_ex * 2

# kita gunakan operasi bagi
w = tensor_ex / 2

print(f"hasil tambah : \n{x}")
print(f"hasil kurang : \n{y}")
print(f"hasil kali : \n{z}")
print(f"hasil bagi : \n{w}")

hasil tambah : 
[[11 12 13]
 [14 15 16]
 [17 18 19]]
hasil kurang : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
hasil kali : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
hasil bagi : 
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [ ]:
# kita bisa gunakan function untuk mengoperasikan tensor
a = tf.multiply(tensor_ex, 10) # perkalian
b = tf.add(tensor_ex, 10) # penjumlahan
c = tf.subtract(tensor_ex, 10) # pengurangan
d = tf.divide(tensor_ex, 10) # pembagian
e = tf.argmax(tensor_ex) # mencari indeks terbesar
f = tf.argmin(tensor_ex) # mencari indeks terkecil

print(f"hasil kali : \n{a}")
print(f"hasil tambah : \n{b}")
print(f"hasil kurang : \n{c}")
print(f"hasil bagi : \n{d}")
print(f"indeks terbesar : {e}")
print(f"indeks terkecil : {f}")

hasil kali : 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
hasil tambah : 
[[11 12 13]
 [14 15 16]
 [17 18 19]]
hasil kurang : 
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
hasil bagi : 
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
indeks terbesar : [2 2 2]
indeks terkecil : [0 0 0]


dengan begini kita bisa mengoperasikan tensor, untuk selebihnya kita bisa melihat dokumentasi tensorflow dengan mengetik tf.math

## MATRIX MULTIPLICATION PART 1

kali ini saya akan membuat matrix multiplication, yaitu pengoperasian antara dua matrix

In [ ]:
# kita buat contoh tensor nya (2 x 2)
tensor_2 = np.arange(1, 5, dtype=np.int32)
tensor_2 = tf.constant(tensor_2, shape=(2, 2))
tensor_3 = np.arange(6, 10, dtype=np.int32)
tensor_3 = tf.constant(tensor_3, shape=(2, 2))

tensor_2, tensor_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 7],
        [8, 9]], dtype=int32)>)

In [ ]:
# kita gabungkan 2 tensor tersebut menggunakan function dari tensorflow
tf.matmul(tensor_2, tensor_3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 25],
       [50, 57]], dtype=int32)>

kita bisa melihat output tersebut, itu adalah hasil perkalian matrix 2 x 2
untuk caranya bisa liat sendiri cara perkalian 2 matrix di google

In [ ]:
# sekarang kita buat 2 tensor dengan shape yang sama, tapi matrix nya berbeda (2 x 3)
tensor_4 = np.arange(1, 7, dtype=np.int32)
tensor_4 = tf.constant(tensor_4, shape=(2, 3))
tensor_5 = np.arange(6, 12, dtype=np.int32)
tensor_5 = tf.constant(tensor_5, shape=(2, 3))

tensor_4, tensor_5

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>)

In [ ]:
# sekarang kita gabungkan kedua tensor tersebut
tf.matmul(tensor_4, tensor_5)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul] name: 

di sini eror karena tidak memenuhi syarat perkalian matrix, walaupun shape nya sama tapi dalam perkaliannya berbeda, seharusnya perkaliannya 2x3 dikali 3x2, jika matrix 2x3 dikali 2x3 maka itu tidak memenuhi persyaratan perkalian matrix makanya eror, pada part 2 akan dijelaskan cara mengatasinya

## MATRIX MULTIPLICATION PART 2

kali ini saya akan melanjutkan matrix yang kemarin, saya akan membahas solusi agar kedua matrix yang eror tersebut bisa dikalikan





In [ ]:
# kita ubah shape nya dari 2x3 menjadi 3x2
tf.reshape(tensor_5, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  7],
       [ 8,  9],
       [10, 11]], dtype=int32)>

In [ ]:
# kita kalikan dengan matrix 3x2
tf.matmul(tensor_4, tf.reshape(tensor_5, shape=(3, 2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 52,  58],
       [124, 139]], dtype=int32)>

In [ ]:
# apa yang terjadi jika x yaitu tensor 4 yang kita ubah shapenya
tf.matmul(tf.reshape(tensor_4, shape=(3, 2)), tensor_5)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 24,  27,  30],
       [ 54,  61,  68],
       [ 84,  95, 106]], dtype=int32)>

terdapat 2 hasil yang kedua hasil tersebut memiliki perbedaan yang sangat signifikan ini dikarenakan perkalian matrix yang berbeda shape

In [ ]:
# kita bisa juga ubah shape menggubakan transpose
tf.transpose(tensor_5)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]], dtype=int32)>

In [ ]:
# lalu kita kalikan
tf.matmul(tensor_4, tf.transpose(tensor_5))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 44,  62],
       [107, 152]], dtype=int32)>

mengapa hasil nya berbeda dengan perkalian sebelumnya?,itu dikarenakan posisi atau urutan elemen matrix yang berbeda, tf.reshape dan tf.transpose sama mengubah bentuk atau shape dari matrix,tapi tf.reshape mengubah shape tanpa memerhatikan urutan elemen yang signifikan, sedangkan tf.transpose mengubah shape sesuai dengan urutan elemen

## MENGGANTI DATATYPE TENSOR

kali ini saya akan mengganti tipe data atau datatype dari tensor menggunakan tf.cast

In [ ]:
# kita buat dulu tensor dengan tipe data float32 dan int32
A = tf.constant([1.2, 3.2,])

B = tf.constant([1, 2, 3])

print(f"tensor A : {A.numpy()}")
print(f"tipe data tensor A : {A.dtype}")
print(f"tensor B : {B.numpy()}")
print(f"tipe data tensor B : {B.dtype}")

tensor A : [1.2 3.2]
tipe data tensor A : <dtype: 'float32'>
tensor B : [1 2 3]
tipe data tensor B : <dtype: 'int32'>


In [ ]:
# kita ubah tipe data nya menggunakan tf.cast
C = tf.cast(A, dtype=tf.float16) # float32 menjadi float16

D = tf.cast(B, dtype=tf.int16) # int32 menjadi int16

E = tf.cast(B, dtype=tf.float32) # int32 menjadi float32

print(f"tensor C : {C.numpy()}")
print(f"tipe data tensor C : {C.dtype}")
print(f"tensor D : {D.numpy()}")
print(f"tipe data tensor D : {D.dtype}")
print(f"tensor E : {E.numpy()}")
print(f"tipe data tensor E : {E.dtype}")

tensor C : [1.2 3.2]
tipe data tensor C : <dtype: 'float16'>
tensor D : [1 2 3]
tipe data tensor D : <dtype: 'int16'>
tensor E : [1. 2. 3.]
tipe data tensor E : <dtype: 'float32'>


## MENCARI NILAI NILAI ABSOLUTE DARI TENSOR
kali ini saya akan mencari nilai absolute seperti mencari nilai minimum, maximum, rata rata, jumlah dan lain lain

In [ ]:
# kita buat tensor dahulu, kali ini saya menggunakan tensor yang isinya nilai acak dengan shape 80
tensor_ex2 = tf.constant(np.random.randint(0, 300, size=80)) # np.random.randint berfungsi membuat array acak
tensor_ex2, tensor_ex2.shape

(<tf.Tensor: shape=(80,), dtype=int64, numpy=
 array([234, 111, 108,  48, 268, 135, 251,  63,  93,  23,  12,  17, 234,
         27, 169,  45,  81, 222, 140,  24, 219, 244, 133, 150,  73, 264,
        126,  46, 116, 272, 224,  44, 241,  63,  23, 211, 257, 283, 101,
        203,  73, 214,  41, 168,   7,  65, 186, 209, 141, 233, 280, 239,
         22, 188, 152, 243, 202, 159, 172, 154,  18,  17, 143,  70,  43,
         40, 168,  20,  84, 274, 253, 161, 251,   4,  28, 256, 234, 258,
        179, 239])>,
 TensorShape([80]))

In [ ]:
# kita cari nilai nilai nya
print(f"nilai minimum : {tf.reduce_min(tensor_ex2)}") # kita cari nilai min
print(f"nilai maximum : {tf.reduce_max(tensor_ex2)}") # kita cari nilai maximum
print(f"nilai rata rata : {tf.reduce_mean(tensor_ex2)}") # kita cari rata rata
print(f"nilai jumlah : {tf.reduce_sum(tensor_ex2)}") # kita cari jumlah
print(f"nilai variansi : {tf.math.reduce_variance(tf.cast(tensor_ex2, dtype=tf.float32))}") # kita cari variansi
print(f"nilai maximum berdasarkan posisi : {tf.argmax(tensor_ex2)}") # kita cari nilai maximum berdasarkan posisi
print(f"nilai minimum berdasarkan posisi : {tf.argmin(tensor_ex2)}") # kita cari nilai minimum berdasarkan posisi

nilai minimum : 4
nilai maximum : 283
nilai rata rata : 143
nilai jumlah : 11486
nilai variansi : 7826.5205078125
nilai maximum berdasarkan posisi : 37
nilai minimum berdasarkan posisi : 73


## BONUS

kali ini saya akan mempelajari tentang segmen tensor, Fungsi ini digunakan dalam TensorFlow untuk menghitung nilai dari setiap segmen dalam sebuah tensor. Segmen-segmen ini didefinisikan oleh sebuah tensor segment_ids yang menunjukkan keanggotaan setiap elemen dalam tensor data ke dalam segmen tertentu.

In [ ]:
# kita buat segmen tensor nya
segmen_tensor = tf.reshape(tensor_ex2, shape=(4, 5, 4)) # kita buat segmen dari tensor yang kita buat sebelumnya
print(f"segmen tensor : \n{segmen_tensor}")
segment_ids1 = tf.constant([0, 0, 1, 1, 2])

segmen tensor : 
[[[234 111 108  48]
  [268 135 251  63]
  [ 93  23  12  17]
  [234  27 169  45]
  [ 81 222 140  24]]

 [[219 244 133 150]
  [ 73 264 126  46]
  [116 272 224  44]
  [241  63  23 211]
  [257 283 101 203]]

 [[ 73 214  41 168]
  [  7  65 186 209]
  [141 233 280 239]
  [ 22 188 152 243]
  [202 159 172 154]]

 [[ 18  17 143  70]
  [ 43  40 168  20]
  [ 84 274 253 161]
  [251   4  28 256]
  [234 258 179 239]]]


segment_ids menunjukkan keanggotaan setiap baris dalam data ke dalam segmen. Dalam contoh ini, baris pertama dan kedua termasuk dalam segmen 0, sedangkan baris ketiga dan keempat termasuk dalam segmen 1, dan baris kelima termasuk segmen 2.

In [ ]:
# kita cari nilai max, min dan lain lain dari segmen
tf.math.segment_max(segmen_tensor[0],segment_ids = segment_ids1) # contoh

print(f"nilai minimum dari segmen : \n {tf.math.segment_min(segmen_tensor[0],segment_ids = segment_ids1)}") # kita cari nilai minimum
print(f"nilai maximum dari segmen : \n {tf.math.segment_max(segmen_tensor[0],segment_ids = segment_ids1)}") # kita cari nilai maximum
print(f"nilai rata rata dari segmen : \n {tf.math.segment_mean(segmen_tensor[0],segment_ids = segment_ids1)}") # kita cari rata rata
print(f"nilai jumlah dari segmen : \n {tf.math.segment_sum(segmen_tensor[0],segment_ids = segment_ids1)}") # kita cari jumlah
print(f"nilai prod dari segmen : \n {tf.math.segment_prod(segmen_tensor[0],segment_ids = segment_ids1)}") # kita cari prod

nilai minimum dari segmen : 
 [[234 111 108  48]
 [ 93  23  12  17]
 [ 81 222 140  24]]
nilai maximum dari segmen : 
 [[268 135 251  63]
 [234  27 169  45]
 [ 81 222 140  24]]
nilai rata rata dari segmen : 
 [[251 123 179  55]
 [163  25  90  31]
 [ 81 222 140  24]]
nilai jumlah dari segmen : 
 [[502 246 359 111]
 [327  50 181  62]
 [ 81 222 140  24]]
nilai prod dari segmen : 
 [[62712 14985 27108  3024]
 [21762   621  2028   765]
 [   81   222   140    24]]


## MENGHAPUS SELURUH DIMENSI YANG BERJUMLAH 1

kali ini saya akan mempelajari cara menghapus 1 dimensi pada tensor

In [ ]:
# kita buat tensor dengan 6 dimensi tensor yang terdiri dari angka 1 sampai 200
tensor_ex3 = tf.constant(np.arange(1, 201, dtype=np.int32), shape=(1, 1, 1, 1, 200))
tensor_ex3, tensor_ex3.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 200), dtype=int32, numpy=
 array([[[[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
             13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
             25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
             37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
             49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
             61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
             73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
             85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
             97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
            109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
            121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
            133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
            145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
      

In [ ]:
# sekarang kita hapus dimensi 1 nya dengan tf.squeeze
tf.squeeze(tensor_ex3)

<tf.Tensor: shape=(200,), dtype=int32, numpy=
array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 1

Dengan ini kita dapat menghapus dimensi yang berjumlah 1 pada tensor

## ONE HOT ENCODING

sebelumnya kita pernah mempelajari one hot encoding pada materi machine learning, namun kali ini saya hanya akan mengulangnya sedikit. One-hot encoding adalah teknik mengubah data kategorikal menjadi representasi numerik yang dapat dipahami oleh model machine learning. Dalam representasi ini, setiap kategori unik akan diubah menjadi sebuah vektor biner (vektor yang hanya berisi nilai 0 atau 1).

In [ ]:
# kita buat list nya dahulu
list_1 = ["merah", "hijau", "biru", "kuning", "ungu",]
list_1

['merah', 'hijau', 'biru', 'kuning', 'ungu']

In [ ]:
# kita ubah jadi angka 1 atau 0 menggunakan metode one hot
color_mapping = {
    "merah": 0,
    "hijau": 1,
    "biru": 2,
    "kuning": 3,
    "ungu": 4
}

numerical_indices = [color_mapping[color] for color in list_1]
tf.one_hot(numerical_indices, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

* color_mapping: Kamus (dictionary) ini digunakan untuk memetakan setiap nama warna ke sebuah angka unik. Ini adalah langkah awal untuk mengubah data kategorikal menjadi numerik.

* numerical_indices = [color_mapping[color] for color in list_1]: List comprehension ini digunakan untuk mengiterasi setiap warna dalam list_1 dan menggantinya dengan indeks numerik yang sesuai berdasarkan color_mapping. Hasilnya adalah sebuah list yang berisi indeks-indeks numerik.

* tf.one_hot(numerical_indices, depth=5): Fungsi tf.one_hot dari TensorFlow digunakan untuk melakukan one-hot encoding.
 * numerical_indices: List yang berisi indeks-indeks numerik yang telah kita dapatkan sebelumnya.
 * depth=5: Menentukan jumlah kolom dalam vektor one-hot. Dalam hal ini, karena kita memiliki 5 warna, maka kita membutuhkan 5 kolom.

sebenarnya ada cara yang lebih mudah yaitu menggunakan scikit learn, itu akan dijelaskan pada materi selanjutnya

## LABEL ENCODING

ini juga sudah pernah saya pelajari di materi machine learning tapi saya hanya ingin ulang sedikit saja. Label encoding adalah teknik yang lebih sederhana. Setiap kategori unik dalam data kategorikal akan dipetakan ke sebuah bilangan bulat. Misalnya, jika kita memiliki kategori warna dengan nilai "merah", "hijau", dan "biru", kita bisa memetakannya ke angka 0, 1, dan 2.

sebenarnya ini tidak jauh berbeda dengan one hot encoding, namun label encoding lebih efisien, tidak banyak memakan tempat dan hemat kolom (jika itu di pandas)

In [ ]:
# kita pakai list yang sama dengan list one hot encoding
# kita import dulu library scikit learn nya, wajib import scikit learn

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoding = label_encoder.fit_transform(list_1)
label_encoding

array([3, 1, 0, 2, 4])

hasilnya tidak jauh berbeda dan lebih singkat

## KUADRAT, AKAR KUADRAT DAN LOG

kali ini saya akan menggunakan operasi matematika seperti kuadrat, akar kuadrat, dan log di tensorflow

In [ ]:
# kita buat tensornya dahulu
tensor_ex4 = tf.constant(np.arange(1, 11, dtype=np.int32))
tensor_ex4

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
# kita coba kuadratkan
kuadrat_otomatis = tf.square(tensor_ex4)

kuadrat_manual = tensor_ex4 ** 2

print(f"kuadrat otomatis : \n{kuadrat_otomatis}")
print(f"kuadrat manual : \n{kuadrat_manual}")

kuadrat otomatis : 
[  1   4   9  16  25  36  49  64  81 100]
kuadrat manual : 
[  1   4   9  16  25  36  49  64  81 100]


hasilnya sama namun cara nya lebih mudah yang otomatis

In [ ]:
# kita coba akar kuadrat kan menggunakan tensor yang sudah kita kuadratkan
akar_otomatis = tf.sqrt(tf.cast(kuadrat_otomatis, dtype=tf.float32))

kuadrat_manual = tf.cast(kuadrat_manual, dtype=tf.float32) # mengubah tipe data ke float32 agar bisa di akar kan
akar_manual = kuadrat_manual ** 0.5 # ini sama seperti kita mengakar kuadrat bilangan

print(f"akar otomatis : \n{akar_otomatis}")
print(f"akar manual : \n{akar_manual}")

akar otomatis : 
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
akar manual : 
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


syarat untuk mengakarkan bilangan kuadrat di tensorflow, tipe datanya harus tf.float32, dan itu bisa diubah menggunakan tf.cast

In [ ]:
# kita coba log kan tensornya
log_otomatis = tf.math.log(tf.cast(tensor_ex4, dtype=tf.float32)) # Cast tensor_ex4 to tf.float32
log_otomatis

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851], dtype=float32)>

sama seperti akar kuadrat, syarat log di tensorflow adalah tipe datanya harus tf.float32, dan itu bisa diubah menggunakan tf.cast

## MENGUBAH TENSOR KE NUMPY DAN NUMPY KE TENSOR

kita bisa mengubah tensor ke numpy dan numpy ke tensor

In [ ]:
# kita buat tensornya dahulu menggunakan np.array (kalau mau pakai np.arange pun juga bisa)
tensor_ex5 = tf.constant(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
tensor_ex5, tensor_ex5.dtype

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>,
 tf.int64)

In [ ]:
# kita ubah tensornya ke numpy
numpy_ex = tensor_ex5.numpy()
numpy_ex, numpy_ex.dtype

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), dtype('int64'))

In [ ]:
# lalu kita ubah numpy ke tensor lagi
tensor_ex6 = tf.constant(numpy_ex)
tensor_ex6, tensor_ex6.dtype

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>,
 tf.int64)