In [ ]:
# pada kali ini saya akan belajar k fold cross validation
# sebenarnya saya tidak terlalu paham tentang ini, jadi jika saya tidak tau, saya bisa menonton di youtube codebasic
# Tapi yang saya tau fungsinya adalah untuk membandingkan metode logika mana yang paling bagus untuk prediksi
# Yang skor nya paling tinggi itulah yang bagus untuk dipakai
# kita pakai 4 metode logika untuk membandingkannya
# pertama kita import library nya dulu

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

# kita pakai dataset iris untuk contoh
iris = load_iris()
dir(iris)

## LogisticRegression

In [6]:
lg = cross_val_score(LogisticRegression(), iris.data, iris.target)
lg

C:\Users\Ryan Akbar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
# kita pakai ini untuk menghitung rata rata skor di atas
np.average(lg)

0.9733333333333334

## Support Vector Machine

In [8]:
svm = cross_val_score(SVC(), iris.data, iris.target)
svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:
np.average(svm)

0.9666666666666666

## RandomForestClassifier

In [10]:
rfc = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [11]:
np.average(rfc)

0.96

## DecisionTree

In [12]:
tree = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
tree

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [13]:
np.average(tree)

0.9600000000000002